#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: UPHANDO EDUCATION SUPPORT INITIATIVE
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  An NGO committed to empowering youth through education, technology, skill acquisition, and healthcare empowerment.
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Uphando Education Support Initiative is a Nigerian-based non-governmental organization (NGO) dedicated to empowering youth through education, technology, skill acquisition, and healthcare initiatives. We are actively involved in the development of artificial intelligence (AI) and language technologies with the goal of seeing them applied in sectors such as agriculture, healthcare, finance, legal services, and other areas that promote social good.
  Through training, mentorship, and practical skill development, we equip young innovators and technologists to create solutions that address real-world challenges, drive innovation, and foster sustainable development across Nigeria and Africa.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: uphando_leadership@googlegroups.com
org_street_address: Odegbami Crescent #Please include suite number on the line below
org_address_suite: Olorunsogo
org_city: Abeokuta
org_state: Ogun State, Nigeria
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  234
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (234) 7064845826
# 1B, Odegbami Crescent, Olorunsogo, Abeokuta, Ogun, Nigeria
#SOCIAL MEDIA
org_twitter_username: uphando-esi
org_facebook_username: uphando-esi
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: three

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
